DELETE http://localhost:3001/api/persons/2

###

GET http://localhost:3001/api/blogs

###

POST http://localhost:3001/api/blogs
content-type: application/json

{
    "title": "D",
    "author": "12345",
    "url": "aaa.com",
    "likes": 10
}