DELETE http://localhost:3001/api/blogs/5ea0f51c9c119c273832ea08
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImNoYXJsaWUiLCJpZCI6IjVlYTUyZTE5OTJkN2QyNjYwM2IwOTU0YSIsImlhdCI6MTU4NzkxMjEyOH0.dSfaIOdf4Plp5Bg2w5e7MgpGatF35g5fnku-AnYooEE

###

GET http://localhost:3001/api/blogs

###

POST http://localhost:3001/api/blogs
Content-Type: application/json
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImNoYXJsaWUiLCJpZCI6IjVlYTUyZTE5OTJkN2QyNjYwM2IwOTU0YSIsImlhdCI6MTU4NzkxMjEyOH0.dSfaIOdf4Plp5Bg2w5e7MgpGatF35g5fnku-AnYooEE

{
    "title": "asjdaskf3",
    "author": "12345",
    "url": "aaa.com",
    "likes": 10
}

###

POST http://localhost:3001/api/login
Content-Type: application/json

{
    "username": "admin",
    "password": "admin"
}

###

POST http://localhost:3001/api/blogs/5ea5a4e43681df774a670cf8/comments
Content-Type: application/json

{
    "content": "lulwide"
}

###

POST http://localhost:3003/exercises
Content-Type: application/json

{
    "daily_exercises": [1, 0, 2, 0, 3, 0, 2.5],
    "target": 2.5
}

###